import React, { useEffect, useState } from 'react';
import { api, apiUrl, ApiUser } from '../lib/api';
import { CalendarDays, CreditCard, ExternalLink, RefreshCw } from 'lucide-react';

let checkoutLoader: Promise<void> | undefined;
function loadCheckout(){return checkoutLoader ||= new Promise<void>((resolve,reject)=>{const s=document.createElement('script');s.src='https://checkout.razorpay.com/v1/checkout.js';s.onload=()=>resolve();s.onerror=()=>{checkoutLoader=undefined;reject(new Error('Payment checkout could not load.'));};document.head.append(s);});}
export function AcademyOperations({ user }: {user:ApiUser|null}) {
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const [studentId,setStudent]=useState(''),[courseId,setCourse]=useState(''),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[status,setStatus]=useState('present'),[reason,setReason]=useState(''),[title,setTitle]=useState('Monthly tuition fee'),[amount,setAmount]=useState('');
 const [accountName,setAccountName]=useState(''),[accountEmail,setAccountEmail]=useState(''),[accountRole,setAccountRole]=useState('parent');
 const [teacherId,setTeacher]=useState(''),[parentId,setParent]=useState('');
 const [classes,setClasses]=useState<any[]>([]),[classroom,setClassroom]=useState<any>(null);
 async function refresh(){try{const d=await api.operations();setData(d);setStudent(s=>s||String(d.students[0]?.id||''));setCourse(s=>s||String(d.courses[0]?.id||''));setError('');}catch(e){setError((e as Error).message);}}
 useEffect(()=>{refresh();if(user?.role==='student')api.classroomStatus().then(setClassroom).catch(()=>{});},[user?.id]);
 async function run(action:()=>Promise<any>,success:string){setBusy(true);setError('');setMessage('');try{await action();setMessage(success);await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function pay(invoice:any){await run(async()=>{const order=await api.paymentOrder(invoice.id);await loadCheckout();const Razorpay=(window as any).Razorpay;new Razorpay({key:order.keyId,order_id:order.orderId,amount:order.amount,currency:'INR',name:'Raghvyon Academy',description:invoice.title,prefill:{email:user?.email,name:user?.name},handler:(result:any)=>run(()=>api.verifyPayment({orderId:result.razorpay_order_id,paymentId:result.razorpay_payment_id,signature:result.razorpay_signature}),'Payment verified. Your receipt is updated.'),theme:{color:'#2454A6'}}).open();},'Checkout opened. Fees update after payment verification.');}
 if(!data)return <section className="ops-panel"><h2>Attendance, leave & fees</h2><p>{error||'Loading your Academy records…'}</p></section>;
 const studentName=(id:number)=>data.students.find((s:any)=>s.id===id)?.name||'Student';
 const courseName=(id:number)=>data.courses.find((c:any)=>c.id===id)?.title||'Course';
 const filters=<><label>Student<select value={studentId} onChange={e=>setStudent(e.target.value)}>{data.students.map((s:any)=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Course<select value={courseId} onChange={e=>setCourse(e.target.value)}>{data.courses.map((c:any)=><option key={c.id} value={c.id}>{c.title}</option>)}</select></label><label>Date<input type="date" value={date} onChange={e=>setDate(e.target.value)} /></label></>;
 return <section className="ops-panel"><div className="ops-heading"><div><p>YOUR ACADEMY, IN ONE PLACE</p><h2>Attendance, leave & fees</h2></div><button onClick={refresh} aria-label="Refresh Academy records"><RefreshCw size={18}/></button></div>{error&&<p className="ops-error" role="alert">{error}</p>}{message&&<p className="ops-success" role="status">{message}</p>}
 {(data.isStaff||user?.role==='parent')&&<form onSubmit={e=>{e.preventDefault();run(()=>data.isStaff?api.markAttendance({studentId:Number(studentId),courseId:Number(courseId),date,status}):api.requestLeave({studentId:Number(studentId),courseId:Number(courseId),date,reason}),data.isStaff?'Attendance saved.':'Leave request sent to your teacher.');}}><h3>{data.isStaff?'Mark class attendance':'Request leave for your child'}</h3><div className="ops-form">{filters}{data.isStaff?<label>Status<select value={status} onChange={e=>setStatus(e.target.value)}>{['present','absent','late','leave'].map(s=><option key={s}>{s}</option>)}</select></label>:<label>Reason<input required minLength={3} maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></label>}<button disabled={busy||!studentId||!courseId} type="submit">{data.isStaff?'Save attendance':'Request leave'}</button></div></form>}
 <div className="ops-columns"><article><h3><CalendarDays size={18}/> Recent attendance</h3>{!data.attendance.length&&<p>No attendance has been recorded yet.</p>}{data.attendance.slice(0,12).map((a:any)=><div className="ops-record" key={a.id}><div><strong>{studentName(a.student_id)}</strong><p>{courseName(a.course_id)} · {a.date}</p></div><span className={'ops-badge '+a.status}>{a.status}</span></div>)}</article><article><h3>Leave requests</h3>{!data.leaves.length&&<p>No leave requests yet.</p>}{data.leaves.slice(0,12).map((l:any)=><div className="ops-record" key={l.id}><div><strong>{studentName(l.student_id)} · {l.date}</strong><p>{l.reason}</p><span className="ops-badge">{l.status}</span></div>{data.isStaff&&l.status==='pending'&&<div><button disabled={busy} onClick={()=>run(()=>api.reviewLeave(l.id,'approved'),'Leave approved.')}>Approve</button><button disabled={busy} onClick={()=>run(()=>api.reviewLeave(l.id,'rejected'),'Leave rejected.')}>Reject</button></div>}</div>)}</article></div>
 <article><h3><CreditCard size={18}/> Fee invoices & receipts</h3>{!data.invoices.length&&<p>No fee invoices yet.</p>}{data.invoices.map((i:any)=><div className="ops-record" key={i.id}><div><strong>{i.title} · {studentName(i.student_id)}</strong><p>Due {i.due_date}{i.paid_at?' · Paid '+i.paid_at:''}</p></div><strong>₹{(i.amount_paise/100).toLocaleString('en-IN')}</strong>{i.status==='paid'?<span className="ops-badge present">Paid</span>:user?.role!=='admin'?<div><button disabled={busy||!data.paymentsConfigured} onClick={()=>run(async()=>{const r=await api.reconcilePayment(i.id);if(!r.paid)throw new Error('No captured payment found yet. Please try again shortly.');},'Payment confirmed.')}>Check payment status</button><button disabled={busy||!data.paymentsConfigured} onClick={()=>pay(i)}>{data.paymentsConfigured?'Pay securely':'Payment setup pending'}</button></div>:<span className="ops-badge absent">Due</span>}</div>)}</article>
 {user?.role==='admin'&&<><form onSubmit={e=>{e.preventDefault();run(async()=>{const result=await api.createAccount({name:accountName,email:accountEmail,role:accountRole});setMessage('Account created. ID: '+result.id);},'Account created. Find its ID in Users.');}}><h3>Create student or parent account</h3><p>The account holder signs in using their verified Google email.</p><div className="ops-form"><label>Name<input required value={accountName} onChange={e=>setAccountName(e.target.value)}/></label><label>Email<input type="email" required value={accountEmail} onChange={e=>setAccountEmail(e.target.value)}/></label><label>Role<select value={accountRole} onChange={e=>setAccountRole(e.target.value)}><option value="parent">Parent</option><option value="student">Student / Teaching account</option></select></label><button disabled={busy}>Create account</button></div></form><form onSubmit={e=>{e.preventDefault();run(()=>api.enrollStudent({studentId:Number(studentId),courseId:Number(courseId)}),'Student enrolled.');}}><h3>Enrol a student</h3><div className="ops-form">{filters}<button disabled={busy}>Enrol student</button></div></form><form onSubmit={e=>{e.preventDefault();run(()=>api.createInvoice({studentId:Number(studentId),title,amountPaise:Math.round(Number(amount)*100),dueDate:date}),'Invoice created.');}}><h3>Create fee invoice</h3><div className="ops-form">{filters}<label>Description<input required value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Amount (₹)<input type="number" min="1" step=".01" required value={amount} onChange={e=>setAmount(e.target.value)}/></label><button disabled={busy}>Create invoice</button></div></form><form onSubmit={e=>{e.preventDefault();run(()=>api.assignTeacher({userId:Number(teacherId),courseId:Number(courseId)}),'Teacher assigned to course.');}}><h3>Assign teacher access</h3><p>Use the verified account ID from the Users tab. Teaching access is limited to the assigned course.</p><div className="ops-form"><label>Teacher account ID<input type="number" min="1" required value={teacherId} onChange={e=>setTeacher(e.target.value)}/></label><label>Course<select value={courseId} onChange={e=>setCourse(e.target.value)}>{data.courses.map((c:any)=><option key={c.id} value={c.id}>{c.title}</option>)}</select></label><button disabled={busy}>Assign teacher</button></div></form><form onSubmit={e=>{e.preventDefault();run(()=>api.linkParent({parentId:Number(parentId),studentId:Number(studentId)}),'Parent link verified.');}}><h3>Verify a parent-child relationship</h3><div className="ops-form"><label>Parent account ID<input type="number" min="1" required value={parentId} onChange={e=>setParent(e.target.value)}/></label><label>Student<select value={studentId} onChange={e=>setStudent(e.target.value)}>{data.students.map((s:any)=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><button disabled={busy}>Verify link</button></div></form></>}
 {user?.role==='student'&&<article><h3>Your Google learning tools</h3><p>First connect your personal Drive for learning files, then Classroom for class links. Each connection asks for your permission.</p><a href={apiUrl('/drive/connect')}>Connect my Google Drive <ExternalLink size={16}/></a><h3>Google Classroom</h3><p>Your personal Google account controls access. Only your classes are shown; this does not create a new Google account.</p>{classroom?.connected?<><button disabled={busy} onClick={()=>run(async()=>{const d=await api.classroomCourses();setClasses(d.courses);},'Classes refreshed.')}>Load my classes</button><button onClick={()=>run(async()=>{await api.classroomDisconnect();setClassroom({connected:false});setClasses([]);},'Classroom disconnected.')}>Disconnect</button></>:classroom?.configured?<a href={apiUrl('/classroom/connect')}>Connect my Google Classroom <ExternalLink size={16}/></a>:<p>Google Classroom configuration pending.</p>}{classes.map(c=><div className="ops-record" key={c.id}><div><strong>{c.name}</strong><p>{c.section}</p></div><a href={c.url} target="_blank" rel="noreferrer">Open class ↗</a></div>)}</article>}
 </section>;
}
